# Generated by Django 4.2.5 on 2023-09-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.FloatField(help_text="in XAF currency"),
        ),
    ]
